### ISSUE TITLE
Can't post site update as Wesley from local instance

### ISSUE THREAD

**Issue by huntertur** [Weasyl/weasyl#1434]
Attempting to post a site update as Wesley from a local instance of Weasyl breaks at least two pages of the website until the database is manually updated. I haven't dug into this enough to tell if this is a code issue or a data issue with the sample database.

# Reproduction steps

1. Follow the local setup steps in the readme.
1. Login as an admin-level or director-level account. (I used `ikani`.)
1. Go to the Administrator Control Panel.
1. Go to Submit Site Update.
1. Enter anything in Title and Content.
1. Check the box that says Post as Wesley.
1. Click Post site update.
1. Verify that going to the homepage results in an error.
1. Verify that viewing the site update page results in an error.

# Fixing this in the local database

1. Run `./wzl exec postgres psql -U weasyl`.
1. Run `UPDATE siteupdate SET wesley = 'f';`.

# Example console output from the error

```
web-1  | {'request_id': 'FYfyFfcE', 'user_id': 2061, 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x78f7c1bab7f0>, 'wsgi.version': (1, 0), 'wsgi.multithread': False, 'wsgi.multiprocess': True, 'wsgi.run_once': False, 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>, 'wsgi.input_terminated': True, 'SERVER_SOFTWARE': 'gunicorn/23.0.0', 'wsgi.input': <gunicorn.http.body.Body object at 0x78f7c1babdc0>, 'gunicorn.socket': <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.25.0.3', 8080), raddr=('172.25.0.2', 38006)>, 'REQUEST_METHOD': 'GET', 'QUERY_STRING': '', 'RAW_URI': '/site-updates/153', 'SERVER_PROTOCOL': 'HTTP/1.0', 'HTTP_HOST': 'weasyl.localhost:8080', 'HTTP_X_FORWARDED_FOR': '::ffff:172.28.0.1', 'HTTP_X_FORWARDED_PROTO': 'http', 'HTTP_CONNECTION': 'close', 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8', 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br, zstd', 'HTTP_REFERER': 'http://weasyl.localhost:8080/admincontrol/siteupdate', 'HTTP_DNT': '1', 'HTTP_COOKIE': 'WZL=**********************', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_SEC_FETCH_DEST': 'document', 'HTTP_SEC_FETCH_MODE': 'navigate', 'HTTP_SEC_FETCH_SITE': 'same-origin', 'HTTP_SEC_FETCH_USER': '?1', 'HTTP_PRIORITY': 'u=0, i', 'wsgi.url_scheme': 'http', 'REMOTE_ADDR': '172.25.0.2', 'REMOTE_PORT': '38006', 'SERVER_NAME': '0.0.0.0', 'SERVER_PORT': '8080', 'PATH_INFO': '/site-updates/153', 'SCRIPT_NAME': ''}
web-1  | Traceback (most recent call last):
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
web-1  |     self.dialect.do_execute(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
web-1  |     cursor.execute(statement, parameters)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/psycopg2cffi/_impl/cursor.py", line 30, in check_closed_
web-1  |     return func(self, *args, **kwargs)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/psycopg2cffi/_impl/cursor.py", line 263, in execute
web-1  |     self._pq_execute(self._query, conn._async)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/psycopg2cffi/_impl/cursor.py", line 696, in _pq_execute
web-1  |     self._pq_fetch()
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/psycopg2cffi/_impl/cursor.py", line 757, in _pq_fetch
web-1  |     raise self._conn._create_exception(cursor=self)
web-1  | psycopg2cffi._impl.exceptions.ProgrammingError: operator does not exist: integer = text
web-1  | LINE 3: WHERE user_media_links.userid = ANY (ARRAY[NULL])
web-1  |                                       ^
web-1  | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
web-1  | 
web-1  | 
web-1  | The above exception was the direct cause of the following exception:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/pyramid/tweens.py", line 41, in excview_tween
web-1  |     response = handler(request)
web-1  |   File "/weasyl/weasyl/middleware.py", line 267, in query_debug_tween
web-1  |     return handler(request)
web-1  |   File "/weasyl/weasyl/middleware.py", line 341, in http2_server_push
web-1  |     resp = handler(request)
web-1  |   File "/weasyl/weasyl/middleware.py", line 295, in database_session_cleanup_tween
web-1  |     return handler(request)
web-1  |   File "/weasyl/weasyl/middleware.py", line 152, in cache_clear_tween
web-1  |     return handler(request)
web-1  |   File "/weasyl/weasyl/middleware.py", line 180, in db_timer_tween
web-1  |     resp = handler(request)
web-1  |   File "/weasyl/weasyl/middleware.py", line 223, in session_tween
web-1  |     return handler(request)
web-1  |   File "/weasyl/weasyl/middleware.py", line 282, in status_check_tween
web-1  |     return handler(request)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/pyramid/router.py", line 143, in handle_request
web-1  |     response = _call_view(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/pyramid/view.py", line 674, in _call_view
web-1  |     response = view_callable(context, request)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/pyramid/config/views.py", line 151, in __call__
web-1  |     return view(context, request)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/pyramid/config/views.py", line 170, in attr_view
web-1  |     return view(context, request)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
web-1  |     return view(context, request)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/pyramid/viewderivers.py", line 392, in viewresult_to_response
web-1  |     result = view(context, request)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/pyramid/viewderivers.py", line 141, in _requestonly_view
web-1  |     response = view(request)
web-1  |   File "/weasyl/weasyl/controllers/general.py", line 188, in site_update_
web-1  |     update = siteupdate.select_view(updateid)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
web-1  |     return caller(func, *(extras + args), **kw)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/cache/region.py", line 1593, in get_or_create_for_user_func
web-1  |     return self.get_or_create(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/cache/region.py", line 1053, in get_or_create
web-1  |     with Lock(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/lock.py", line 185, in __enter__
web-1  |     return self._enter()
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/lock.py", line 94, in _enter
web-1  |     generated = self._enter_create(value, createdtime)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/lock.py", line 178, in _enter_create
web-1  |     return self.creator()
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/cache/region.py", line 1006, in gen_value
web-1  |     created_value = creator(
web-1  |   File "/weasyl/weasyl/siteupdate.py", line 87, in select_view
web-1  |     "user_media": media.get_user_media(update.userid),
web-1  |   File "/weasyl/weasyl/media.py", line 46, in get_user_media
web-1  |     return get_multi_user_media(userid)[0]
web-1  |   File "/weasyl/weasyl/media.py", line 35, in get_multi_user_media
web-1  |     ret = libweasylmedia.get_multi_user_media(*userids)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
web-1  |     return caller(func, *(extras + args), **kw)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/cache/region.py", line 1831, in get_or_create_for_user_func
web-1  |     result = self.get_or_create_multi(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/cache/region.py", line 1179, in get_or_create_multi
web-1  |     new_values = creator(*keys_to_get)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/dogpile/cache/region.py", line 1794, in creator
web-1  |     return user_func(*[key_lookup[k] for k in keys_to_create])
web-1  |   File "/weasyl/libweasyl/media.py", line 14, in get_multi_user_media
web-1  |     return UserMediaLink.bucket_links(userids)
web-1  |   File "/weasyl/libweasyl/models/media.py", line 135, in bucket_links
web-1  |     for link in q:
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2901, in __iter__
web-1  |     result = self._iter()
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
web-1  |     result = self.session.execute(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
web-1  |     result = conn._execute_20(statement, params or {}, execution_options)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
web-1  |     return meth(self, args_10style, kwargs_10style, execution_options)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
web-1  |     return connection._execute_clauseelement(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
web-1  |     ret = self._execute_context(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
web-1  |     self._handle_dbapi_exception(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
web-1  |     util.raise_(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
web-1  |     raise exception
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
web-1  |     self.dialect.do_execute(
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
web-1  |     cursor.execute(statement, parameters)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/psycopg2cffi/_impl/cursor.py", line 30, in check_closed_
web-1  |     return func(self, *args, **kwargs)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/psycopg2cffi/_impl/cursor.py", line 263, in execute
web-1  |     self._pq_execute(self._query, conn._async)
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/psycopg2cffi/_impl/cursor.py", line 696, in _pq_execute
web-1  |     self._pq_fetch()
web-1  |   File "/weasyl/.venv/lib/python3.10/site-packages/psycopg2cffi/_impl/cursor.py", line 757, in _pq_fetch
web-1  |     raise self._conn._create_exception(cursor=self)
web-1  | sqlalchemy.exc.ProgrammingError: (psycopg2cffi._impl.exceptions.ProgrammingError) operator does not exist: integer = text
web-1  | LINE 3: WHERE user_media_links.userid = ANY (ARRAY[NULL])
web-1  |                                       ^
web-1  | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
web-1  | 
web-1  | [SQL: SELECT user_media_links.linkid AS user_media_links_linkid, user_media_links.mediaid AS user_media_links_mediaid, user_media_links.userid AS user_media_links_userid, user_media_links.link_type AS user_media_links_link_type, media_1.mediaid AS media_1_mediaid, media_1.file_type AS media_1_file_type, media_1.attributes AS media_1_attributes, media_1.sha256 AS media_1_sha256 
web-1  | FROM user_media_links LEFT OUTER JOIN media AS media_1 ON media_1.mediaid = user_media_links.mediaid 
web-1  | WHERE user_media_links.userid = ANY (%(param_1)s)]
web-1  | [parameters: {'param_1': [None]}]
web-1  | (Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by charmander** [comment]
Yeah, I need to make a new version of the sample database that includes Wesley.

**Comment by charmander** [comment]
Yeah, I need to make a new version of the sample database that includes Wesley. In the meantime, though, you can set `WESLEY` to any user in the staff configuration ([relevant part of `wzl config`](https://github.com/Weasyl/weasyl/blob/a2c4244d384283a9990bd61f42c73b40cd454dd3/wzl#L49)).
