### ISSUE TITLE
Adapt to Raven 5.x API change

### ISSUE THREAD

**Issue by skylerbunny** [Weasyl/weasyl#78]
The following errors get logged when our code uses a 5.x (relatively new) version of Raven.  We are currently on 5.0.21. In production these get logged every three minutes.

```
2016-06-20_19:55:01.56840 2016-06-20T12:55:01-0700 [-] refreshed active user counts
2016-06-20_19:58:51.25545 2016-06-20T12:58:51-0700 [twisted.web.client._HTTP11ClientFactory#info] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7fb3389e1dd0>
2016-06-20_19:58:51.25615 2016-06-20T12:58:51-0700 [wsgi] Traceback (most recent call last):
2016-06-20_19:58:51.25617 	  File "/var/lib/weasyl/weasyl/weasyl-env/local/lib/python2.7/site-packages/web/application.py", line 239, in process
2016-06-20_19:58:51.25617 	    return self.handle()
2016-06-20_19:58:51.25617 	  File "/var/lib/weasyl/weasyl/weasyl/middleware.py", line 106, in weasyl_exception_processor
2016-06-20_19:58:51.25618 	    event_id, = web.ctx.env['raven.captureException'](request_id=request_id)
2016-06-20_19:58:51.25618 	ValueError: too many values to unpack
2016-06-20_19:58:51.25618
2016-06-20_19:58:51.25640 2016-06-20T12:58:51-0700 [wsgi]
2016-06-20_19:58:51.25641
```

It is currently talking to Sentry 8.5.1.

**Comment by weykent** [comment]
https://github.com/getsentry/raven-python/commit/8c89e45a68135095f130ad8a9c1a71cfe5c67b5f Looks like it now returns just the `event_id`, without being wrapped in a one-tuple.

**Comment by skylerbunny** [comment]
From https://github.com/getsentry/raven-python/blob/master/CHANGES :

Version 5.2.0: Protocol version is now 6 (requires Sentry 7.0 or newer).
